environment: production

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: postgres
      mode: always
