#Be sure to change volumn location
#start:   docker-compose -f docker-dbonly.yml up -d
#stop:    docker-compse -f docker-dbonly.yml down

version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: ./.env
    volumes:
      - "$POSTGRES_EXTERNAL_LOC:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
  mongo:
    container_name: mongo
    image: mongo
    env_file: ./.env
    volumes:
      - "$MONGO_EXTERNAL_LOC:/data/db"
    restart: always
    ports:
      - "27017:27017"
